### ISSUE TITLE
redmine 5.0.2

### ISSUE THREAD

**Issue by ashrafalzyoud** [Gzbox/select_to_select2#1]
can u update it?

**Comment by Gzbox** [comment]
> can u update it?

sorry we are using `4.2.3`, I cannot guarantee that `5.0.2` will work.

**Comment by ashrafalzyoud** [comment]
TEST IT PLZ

**Comment by ashrafalzyoud** [comment]
![select2](https://user-images.githubusercontent.com/50211455/180457846-d27b4231-347d-48b4-9d6e-b6ea42bddf9c.png)

**Comment by ashrafalzyoud** [comment]
@Gzbox

**Comment by Gzbox** [comment]
> ![select2](https://user-images.githubusercontent.com/50211455/180457846-d27b4231-347d-48b4-9d6e-b6ea42bddf9c.png)

Sorry, I'm too busy right now to have no time to test and work on it
